server:
  # 网关端口
  port: 10010
spring:
  application:
    # 服务名称
    name: gateway
  cloud:
    nacos:
      # nacos服务地址
      server-addr: myvm:8848
    gateway:
      # 网关路由配置
      routes: # 路由规则配置
        - id: user-service-route # 路由id，自定义
          uri: lb://user-service # 路由目标地址。 lb:loadBalance 后接spring.application.name
          predicates: # 路由断言，判断请求是否符合路由规则的条件
            - Path=/user/** # 该路径匹配，只要以/user/ 打头就符合要求
          filters:
            - AddRequestHeader=Slogan, "键盘敲烂，月薪过万"
        - id: order-serivce-route
          uri: lb://order-service
          predicates:
            - Path=/order/**