server:
  # 服务端口
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 集群名称
        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
#eureka:
#  client:
#    service-url:
#      # eureka的地址信息
#      defaultZone: Http://localhost:10086/eureka